update tag Name for list of repos
cloudposse/terraform-aws-ecr pull request #81
Opened 2021-06-16 13:33 UTC by dmitriy-lukyanchikov

## what
fix tag Name for the list of repos so every repo will have it own tag Name that will be equal to name of repo

## why
because right now there is only one tag Name for all list of repos

2021-06-16 16:01 UTC, korenyoni requested changes
We shouldn't be manipulating the tags map directly. We should instead be instantiating the `null_label` module for each of the repositories.

```
locals {
  ...
  repository_names  = toset(module.this.enabled ? local.image_names : [])
}
```

```
module "repository_label" {
  for_each = local.repository_names

  source  = "cloudposse/label/null"
  version = "0.24.1"

  context = module.this.context
  attributes = [each.value]
}
```

Finally, we can use the tags from this module instantiation in the resource:

```
resource "aws_ecr_repository" "name" {
  for_each             = local.repository_names
  name                 = each.value
  image_tag_mutability = var.image_tag_mutability

  ...

  tags = module.repository_label[each.value].tags
}
```

The result is that the repository will keep all of the context attribute in its name tag (Namespace, Stage, Name, Attributes)

And, the repository name will only be the name of the image:

![CleanShot 2021-06-16 at 11 58 26@2x](https://user-images.githubusercontent.com/10080107/122253520-3dad8700-ce9a-11eb-845e-bf2e9744db8d.png)

```
      + tags                 = {
          + "Attributes" = "redis"
          + "Name"       = "eg-dev-app-redis"
          + "Namespace"  = "eg"
          + "Stage"      = "dev"
        }

```

2021-06-16 16:01 UTC, korenyoni commented on main.tf
> +  tags = merge(module.this.tags, { Name = each.value })
```suggestion
  tags = module.repository_label[each.value].tags
```

2021-06-30 16:40 UTC, Gowiem commented
@dmitriy-lukyanchikov friendly ping on this one. Can you update to @korenyoni's suggestion?

2021-07-01 07:27 UTC, dmitriy-lukyanchikov commented
probably i will close this ticket for now there is too much to test for me right now if you want to change it on your own feel free

2021-07-01 07:27 UTC, closed without merging